### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/nutshell-droids#2]
# User Stories
- [x] As a user, when I am unauthenticated I should be able to see the dashboard (Read only). #36
- [ ] As a user, when I am authenticated I should be able to perform all actions on the dashboard (full CRUD).	#36 
- [x] As a user, I should be able to login via google. #37 
- [x] As a user, I should be able to logout #37
