### ISSUE TITLE
Airports Collection

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/nutshell-droids#3]
# User Stories
- [x] As a user, I should be able to view all the airports PanAm can be hangered. #31 
- [ ] As a user, I should be able to add a new airport. #19 
- [ ] As a user, I should be able to edit an airport. #27 
- [x] As a user, I should be able to delete an airport. #32

**Comment by stephencastaneda** [comment]
![Screen Shot 2020-04-14 at 9 32 48 AM](https://user-images.githubusercontent.com/59769978/79282953-174a2100-7e7c-11ea-9dbb-213ddef53ba1.png)

**Comment by sarahholder** [comment]
{
	"airport1": {
		"city": "Kansas City",
		"state": "MO",
		"country": "US",
		"airport code": "MCI",
		"is international": "False"
	},
	"airport2": {
		"city": "Dubai",
		"state": "N/A",
		"country": "UAE",
		"airport code": "DXB",
		"is international": "True"
	},
	"airport3": {
		"city": "New York City",
		"state": "NY",
		"country": "US",
		"airport code": "JFK",
		"is international": "True"
	},
	"airport4": {
		"city": "Honolulu",
		"state": "Hawaii",
		"country": "US",
		"airport code": "HNL",
		"is international": "No"
	},
	"airport5": {
		"city": "Edinburgh",
		"state": "N/A",
		"country": "Scotland",
		"airport code": "EDI",
		"is international": "Yes"
	}
}
