### ISSUE TITLE
Planes Collection

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/nutshell-droids#4]
# User Stories
- [x] As a user, I should be able to view all the planes PanAm owns. #35 
- [ ] As a user, I should be able to create a new plane. #21 
- [ ] As a user, I should be able to edit a plane. #34 
- [ ] As a user, I should be able to delete a plane #33

**Comment by stephencastaneda** [comment]
![Screen Shot 2020-04-14 at 9 33 00 AM](https://user-images.githubusercontent.com/59769978/79283029-42cd0b80-7e7c-11ea-9b2b-77e25ec4cb39.png)
