### ISSUE TITLE
Crew Collection

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/nutshell-droids#5]
# User Stories
- [x] As a user, I should be able to view all crew members on the team. #22 
- [ ] As a user, I should be able to add a crew member to the team.  #20 
- [ ] As a user, I should be able to edit a crew member on the team. #26 
- [ ] As a user, I should be able to remove a crew member from the team. #25

**Comment by stephencastaneda** [comment]
![Screen Shot 2020-04-14 at 9 32 36 AM](https://user-images.githubusercontent.com/59769978/79282997-321c9580-7e7c-11ea-989e-137ffcbe38ec.png)
