### ISSUE TITLE
Foods Collection

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/nutshell-droids#6]
- [ ] As a user, I should be able to view all the food options available for flights. #15 
- [ ] As a user, I should be able to add items to the menu. #17 
- [ ] As a user, I should be able to edit items on the menu. #16 
- [ ] As a user, I should be able to delete items on the menu. #14

**Comment by stephencastaneda** [comment]
![Screen Shot 2020-04-14 at 9 33 12 AM](https://user-images.githubusercontent.com/59769978/79282975-27620080-7e7c-11ea-8c4c-79401e1912b7.png)
